### ISSUE TITLE
有机会出绝对深度版本的Depth anything tensorrt 加速的程式码吗？

### ISSUE THREAD

**Issue by bhsud** [thinvy/DepthAnythingTensorrtDeploy#2]

**Comment by QinnyuLan** [comment]
算法层面仅依靠单张图片的单目深度估计无法获得绝对深度信息

**Comment by bhsud** [comment]
就是该如何使用depth anything推出的绝对深度版本去做Tensorrt加速
[https://github.com/LiheYoung/Depth-Anything/tree/main/metric_depth](url)

**Comment by QinnyuLan** [comment]
模型结构是一样的，只是对度量深度信息进行微调，下载metric_depth里的预训练权重按readme中的流程正常转换模型就可以

**Comment by bhsud** [comment]
好的 我试试看
感谢

**Comment by lin-voxvision** [comment]
> 好的 我试试看 感谢

Hi, 你好，请问对metric的模型转换成trt模型推理成功了么
